### ISSUE TITLE
你好,请问能否提供TC的config配置文件信息

### ISSUE THREAD

**Issue by dsadsaad** [tanzzj/springcloud-seata-feign#1]
你好,请问能否提供TC的config配置文件信息.

**Comment by dsadsaad** [comment]
按照官方文档搭建了TC,运行此demo,在nacos能看到成功注册了TC,RM,TM但是RM,TM出现了以下报错
 no available service found in cluster 'guangzhou', please make sure registry config correct and keep your seata server running

**Comment by tanzzj** [comment]
> 按照官方文档搭建了TC,运行此demo,在nacos能看到成功注册了TC,RM,TM但是RM,TM出现了以下报错
> no available service found in cluster 'guangzhou', please make sure registry config correct and keep your seata server running

这个问题看一下官网的这篇：
http://seata.io/zh-cn/docs/user/txgroup/transaction-group-and-ha.html

主要是client端找不到服务端集群导致的

**Comment by tanzzj** [comment]
> 按照官方文档搭建了TC,运行此demo,在nacos能看到成功注册了TC,RM,TM但是RM,TM出现了以下报错
> no available service found in cluster 'guangzhou', please make sure registry config correct and keep your seata server running

`registry {
  type = "nacos"
  loadBalance = "RandomLoadBalance"
  loadBalanceVirtualNodes = 10

  nacos {
    application = "seata-server"
    serverAddr = ""
    group = "DEFAULT_GROUP"
    namespace = ""
    cluster = "guangzhou"
    username = ""
    password = ""
  }
}`

**Comment by tanzzj** [comment]
> 按照官方文档搭建了TC,运行此demo,在nacos能看到成功注册了TC,RM,TM但是RM,TM出现了以下报错
> no available service found in cluster 'guangzhou', please make sure registry config correct and keep your seata server running

`registry {
  type = "nacos"
  loadBalance = "RandomLoadBalance"
  loadBalanceVirtualNodes = 10

  nacos {
    application = "seata-server"
    serverAddr = ""
    group = "DEFAULT_GROUP"
    namespace = ""
    cluster = "guangzhou"
    username = ""
    password = ""
  }
}`

**Comment by tanzzj** [comment]
> 按照官方文档搭建了TC,运行此demo,在nacos能看到成功注册了TC,RM,TM但是RM,TM出现了以下报错
> no available service found in cluster 'guangzhou', please make sure registry config correct and keep your seata server running

registry {
  type = "nacos"
  loadBalance = "RandomLoadBalance"
  loadBalanceVirtualNodes = 10

  nacos {
    application = "seata-server"
    serverAddr = ""
    group = "DEFAULT_GROUP"
    namespace = ""
    cluster = "guangzhou"
    username = ""
    password = ""
  }
}

**Comment by dsadsaad** [comment]
> > 按照官方文档搭建了TC,运行此demo,在nacos能看到成功注册了TC,RM,TM但是RM,TM出现了以下报错
> > no available service found in cluster 'guangzhou', please make sure registry config correct and keep your seata server running
> 
> registry {
> type = "nacos"
> loadBalance = "RandomLoadBalance"
> loadBalanceVirtualNodes = 10
> 
> nacos {
> application = "seata-server"
> serverAddr = ""
> group = "DEFAULT_GROUP"
> namespace = ""
> cluster = "guangzhou"
> username = ""
> password = ""
> }
> }

你好,能否再提供一下完整的seata-server config.txt 文件配置

**Comment by dsadsaad** [comment]
transport.type=TCP
transport.server=NIO
transport.heartbeat=true
transport.enableClientBatchSendRequest=false
transport.threadFactory.bossThreadPrefix=NettyBoss
transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
transport.threadFactory.shareBossWorker=false
transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
transport.threadFactory.clientSelectorThreadSize=1
transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
transport.threadFactory.bossThreadSize=1
transport.threadFactory.workerThreadSize=default
transport.shutdown.wait=3
猜测应该是这个配置为guangzhou,验证中
**service.vgroupMapping.my_test_tx_group=default**
service.default.grouplist=127.0.0.1:8091
service.enableDegrade=false

**Comment by tanzzj** [comment]
> transport.type=TCP
> transport.server=NIO
> transport.heartbeat=true
> transport.enableClientBatchSendRequest=false
> transport.threadFactory.bossThreadPrefix=NettyBoss
> transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
> transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
> transport.threadFactory.shareBossWorker=false
> transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
> transport.threadFactory.clientSelectorThreadSize=1
> transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
> transport.threadFactory.bossThreadSize=1
> transport.threadFactory.workerThreadSize=default
> transport.shutdown.wait=3
> 猜测应该是这个配置为guangzhou,验证中
> **service.vgroupMapping.my_test_tx_group=default**
> service.default.grouplist=127.0.0.1:8091
> service.enableDegrade=false

先看下官网关于事务分组的介绍，你就知道这个地方怎么配置了

**Comment by dsadsaad** [comment]
> > transport.type=TCP
> > transport.server=NIO
> > transport.heartbeat=true
> > transport.enableClientBatchSendRequest=false
> > transport.threadFactory.bossThreadPrefix=NettyBoss
> > transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
> > transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
> > transport.threadFactory.shareBossWorker=false
> > transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
> > transport.threadFactory.clientSelectorThreadSize=1
> > transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
> > transport.threadFactory.bossThreadSize=1
> > transport.threadFactory.workerThreadSize=default
> > transport.shutdown.wait=3
> > 猜测应该是这个配置为guangzhou,验证中
> > **service.vgroupMapping.my_test_tx_group=default**
> > service.default.grouplist=127.0.0.1:8091
> > service.enableDegrade=false
> 
> 先看下官网关于事务分组的介绍，你就知道这个地方怎么配置了

感谢,已跑通
